[package]
name = "apron-gateway"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
actix-web = "3.0"
serde = { version = "1.0" }
serde_json = "1.0.59"
uuid = { version = "0.7", features = ["serde", "v4"] }